### PR TITLE
Shwetaoj/container build readme

### PR DESCRIPTION
**Pull request by shwetaoj**
Add readme with instructions to create a development container using 2.3 branch.
https://github.com/Intel-tensorflow/tensorflow/blob/shwetaoj/container_build_readme/Intel-tensorflow-build-container.md

### CODE REVIEW

**Review by chuanqi129 — APPROVED** [review]

**Review by ashahba — APPROVED** [review]
LGTM

**Comment by ashahba** [comment]
Thanks @shwetaoj for this PR. We will `Squash and merge` once @agramesh1 also approves.

**Comment by justkw** [comment]
I've tested the steps in the Readme successfully, so it's ready to go.

**Review by nammbash — APPROVED** [review]
Looks cleaner and good to me. 
Note: I did not run it step by step. But it looks fine on Glancing at it.

**Pull request merged**
